#!/usr/bin/env node
/**
 * sync-kv.js — keep the backlink directory in sync between the Node server
 * (data/backlinks.json) and the Workers KV namespace.
 *
 * Usage:
 *   npm run sync:kv                 push local data → KV, then verify
 *   npm run sync:kv -- --pull       merge KV → local, then converge KV to
 *                                   the same union and verify both sides
 *   npm run sync:kv -- --check      verify only, without writing
 *   node scripts/sync-kv.js --check
 *
 * Requires wrangler auth (`npx wrangler login` or CLOUDFLARE_API_TOKEN).
 * The namespace id is read from wrangler.toml — single source of truth.
 * Note: wrangler 4 defaults kv commands to LOCAL storage; --remote is
 * mandatory here and is asserted in the spawned arguments.
 */
'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_FILE = path.join(ROOT, 'data', 'backlinks.json');
const WRANGLER_TOML = path.join(ROOT, 'wrangler.toml');
const KEY = 'backlinks';

const CHECK_ONLY = process.argv.includes('--check');
const PULL = process.argv.includes('--pull');
if (CHECK_ONLY && PULL) {
  console.error('ERROR: --check and --pull are mutually exclusive.');
  process.exit(2);
}

function readNamespaceId() {
  const toml = fs.readFileSync(WRANGLER_TOML, 'utf8');
  const m = toml.match(/\[\[kv_namespaces\]\][\s\S]*?id\s*=\s*"([0-9a-f]+)"/);
  if (!m) {
    console.error(`ERROR: no [[kv_namespaces]] id found in ${path.relative(ROOT, WRANGLER_TOML)}`);
    process.exit(1);
  }
  return m[1];
}

function readLocalData() {
  // A missing file is normal on fresh clones (data/backlinks.json is
  // gitignored) — --pull then starts from an empty local store and the merge
  // adopts everything from KV. Any other problem is still fatal.
  if (!fs.existsSync(DATA_FILE)) {
    if (PULL) return [];
    console.error(`ERROR: ${path.relative(ROOT, DATA_FILE)} not found. For a fresh clone, run --pull to adopt the KV directory.`);
    process.exit(1);
  }
  try {
    const parsed = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
    if (!Array.isArray(parsed)) throw new Error('not a JSON array');
    return parsed;
  } catch (e) {
    console.error(`ERROR: cannot read ${path.relative(ROOT, DATA_FILE)}: ${e.message}`);
    process.exit(1);
  }
}

function runWrangler(args, opts = {}) {
  // execSync takes a proper command string (no DEP0190 array+shell warning,
  // and cmd.exe handles a single plain string better than quoted tokens).
  const q = process.platform === 'win32';
  const quote = (s) => (q && /[\s"]/.test(s) ? `"${s.replace(/"/g, '\\"')}"` : s);
  const cmd = ['npx', ...args].map(quote).join(' ');
  return execSync(cmd, { stdio: 'inherit', shell: true, ...opts });
}

function kvKeyPut(namespaceId, file) {
  // --remote is the whole point of this script: without it wrangler 4 writes
  // to the local dev store and the real namespace never changes.
  const args = ['wrangler', 'kv', 'key', 'put', KEY, '--path', file,
    '--namespace-id', namespaceId, '--remote'];
  console.log(`$ npx ${args.join(' ')}`);
  runWrangler(args);
}

function kvKeyGet(namespaceId) {
  // --remote + fresh process: bypasses the edge cache and any isolate cache,
  // so this is the authoritative state of the namespace.
  const args = ['wrangler', 'kv', 'key', 'get', KEY, '--namespace-id', namespaceId, '--remote'];
  return runWrangler(args, {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
    maxBuffer: 16 * 1024 * 1024,
  });
}

const hostnameOf = (u) => {
  try { return new URL(u).hostname.replace(/^www\./, '').toLowerCase(); } catch { return null; }
};

/**
 * Merge the two sides of the directory without losing anything:
 * union by id, then dedupe identical hostnames (keeping the newer
 * submission — ids begin with a Base36 timestamp, as generated by both
 * runtimes), then sort chronologically by id so the merged output matches
 * what a single store would contain.
 */
function mergeListings(local, remote) {
  const byId = new Map();
  for (const x of local) if (x && x.id) byId.set(x.id, x);
  for (const x of remote) if (x && x.id) byId.set(x.id, x);
  const newerId = (a, b) => (String(a.id) >= String(b.id) ? a : b);
  const byHost = new Map();
  for (const x of byId.values()) {
    const h = hostnameOf(x.website);
    if (!h) continue;
    byHost.set(h, byHost.has(h) ? newerId(byHost.get(h), x) : x);
  }
  return [...byHost.values()].sort((a, b) =>
    (String(a.id) < String(b.id) ? -1 : String(a.id) > String(b.id) ? 1 : 0));
}

function summarize(list) {
  return list.map((x) => x.name || x.id || '?').join(', ');
}

function main() {
  const namespaceId = readNamespaceId();
  console.log(`namespace: ${namespaceId}`);

  const local = readLocalData();

  let remote;
  try {
    remote = JSON.parse(kvKeyGet(namespaceId));
  } catch (e) {
    console.error(`ERROR: remote read failed: ${e.message.trim()}`);
    process.exit(1);
  }
  if (!Array.isArray(remote)) {
    console.error('ERROR: remote value is not a JSON array');
    process.exit(1);
  }

  if (CHECK_ONLY) {
    const same = JSON.stringify(local) === JSON.stringify(remote);
    console.log(`local: ${local.length} listings [${summarize(local)}]`);
    console.log(`remote: ${remote.length} listings [${summarize(remote)}]`);
    if (!same) {
      console.error('CHECK FAILED — local and KV differ.');
      console.error('  new listings on Workers → `npm run sync:kv -- --pull` (merges both sides)');
      console.error('  local is the source of truth → `npm run sync:kv` (overwrites KV)');
      process.exit(1);
    }
    console.log('CHECK PASSED — local data and KV match.');
    return;
  }

  if (PULL) {
    const merged = mergeListings(local, remote);
    const localChanged = JSON.stringify(local) !== JSON.stringify(merged);
    const remoteChanged = JSON.stringify(remote) !== JSON.stringify(merged);
    console.log(`local: ${local.length} listings, KV: ${remote.length} listings, merged union: ${merged.length} listings`);
    if (!localChanged && !remoteChanged) {
      console.log('PULL OK — both sides already identical, nothing to do.');
      return;
    }
    if (localChanged) {
      fs.writeFileSync(DATA_FILE, JSON.stringify(merged, null, 2));
      console.log(`wrote ${merged.length} listing(s) to ${path.relative(ROOT, DATA_FILE)}`);
    }
    if (remoteChanged) {
      kvKeyPut(namespaceId, DATA_FILE);
      // Verify KV converged to the merged union (guards against silent no-ops).
      let verify;
      try {
        verify = JSON.parse(kvKeyGet(namespaceId));
      } catch (e) {
        console.error(`ERROR: post-write verification read failed: ${e.message.trim()}`);
        process.exit(1);
      }
      if (JSON.stringify(verify) !== JSON.stringify(merged)) {
        console.error('SYNC FAILED — KV read-back differs from the merged union (KV propagation lag?).');
        console.error('Re-run `npm run sync:kv -- --pull` shortly.');
        process.exit(1);
      }
      console.log(`KV updated to the merged union (${merged.length} listing(s))`);
    }
    console.log(`PULL OK — [${summarize(merged)}]`);
    return;
  }

  // Default: push local → KV.
  kvKeyPut(namespaceId, DATA_FILE);

  // Verify the write actually landed (guards against silent no-ops). The
  // remote was already read above; re-read after the write.
  let verify;
  try {
    verify = JSON.parse(kvKeyGet(namespaceId));
  } catch (e) {
    console.error(`ERROR: post-write verification read failed: ${e.message.trim()}`);
    process.exit(1);
  }
  const same = JSON.stringify(local) === JSON.stringify(verify);
  console.log(`local: ${local.length} listings`);
  console.log(`KV: ${Array.isArray(verify) ? verify.length : '?'} listings`);
  if (!same) {
    console.error('SYNC FAILED — verification read-back differs from local data (KV propagation lag?).');
    console.error('Re-run `npm run sync:kv` shortly, or inspect with:');
    console.error(`  npx wrangler kv key get ${KEY} --namespace-id ${namespaceId} --remote`);
    process.exit(1);
  }
  console.log(`SYNC OK — ${verify.length} listing(s) verified in KV: [${summarize(verify)}]`);
  console.log('Note: edge readers may lag up to ~60s (KV eventual consistency + worker cache TTL).');
}

main();
